- name: Install bind9 packages
  become: yes
  apt:
      name: ['bind9', 'bind9utils', 'bind9-doc'] 
      state: present 
      update_cache: yes

- name: Setting up bind options
  become: yes
  template:
      src: templates/named.conf.options.j2
      dest: /etc/bind/named.conf.options

- name: Creating local bind configs
  become: yes
  template:
      src: templates/named.conf.local.j2
      dest: /etc/bind/named.conf.local

- name: Create zones directory
  become: yes
  file:
      state: directory
      name: /etc/bind/zones

- name: Creating log directory
  become: yes
  file:
      state: directory
      name: /var/log/named

- name: Touching log file
  become: yes
  file:
    state: touch
    name: /var/log/named/querylog
    owner: root
    group: bind
    mode: 0660

- name: Creating bind db file
  become: yes
  template:
      src: templates/db.local.j2
      dest: "/etc/bind/zones/db.{{ auth_domain | mandatory }}"

- name: Restart bind service
  become: yes
  systemd:
      name: bind9
      state: restarted
      enabled: yes
